const qs=(s,r=document)=>r.querySelector(s);const qsa=(s,r=document)=>[...r.querySelectorAll(s)];

const menuButton=qs('#menu-button');const mobileMenu=qs('#mobile-menu');if(menuButton&&mobileMenu){menuButton.addEventListener('click',()=>{const open=mobileMenu.classList.toggle('is-open');menuButton.setAttribute('aria-expanded',String(open))});qsa('a',mobileMenu).forEach(a=>a.addEventListener('click',()=>{mobileMenu.classList.remove('is-open');menuButton.setAttribute('aria-expanded','false')}))}

const progress=qs('#scroll-progress');const syncProgress=()=>{if(!progress)return;const max=document.documentElement.scrollHeight-innerHeight;progress.style.width=`${max>0?scrollY/max*100:0}%`};addEventListener('scroll',syncProgress,{passive:true});syncProgress();

const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');observer.unobserve(e.target)}}),{threshold:.12,rootMargin:'0px 0px -40px'});qsa('.reveal').forEach(el=>observer.observe(el));

const consoleData={workflow:{title:'Workflow redesign',copy:'Find the high-friction decisions, handoffs, and repetitive work before choosing an AI tool.',signal:'Redesign first. Automate second.',bars:['88%','63%','74%']},data:{title:'Data readiness',copy:'Make enterprise knowledge discoverable, permissioned, contextual, and reusable by both people and AI systems.',signal:'Context is infrastructure.',bars:['52%','81%','66%']},agents:{title:'Agentic operations',copy:'Define what agents may observe, decide, and execute—and where humans must approve, intervene, or own the outcome.',signal:'Autonomy needs boundaries.',bars:['76%','58%','91%']},governance:{title:'Control by design',copy:'Engineer monitoring, auditability, escalation paths, access controls, and failure handling before autonomous systems scale.',signal:'Governance should run at machine speed.',bars:['69%','84%','73%']}};
qsa('.console-tab').forEach(btn=>btn.addEventListener('click',()=>{qsa('.console-tab').forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');const d=consoleData[btn.dataset.console];qs('#console-title').textContent=d.title;qs('#console-copy').textContent=d.copy;qs('#console-signal').textContent=d.signal;qsa('#console-bars span').forEach((s,i)=>s.style.setProperty('--w',d.bars[i])}));

const capabilities={strategy:{code:'CAPABILITY / 01',title:'AI Transformation Strategy',copy:'Translate business priorities into a practical AI roadmap: use cases, sequencing, operating model, costs, risks, and success metrics.',questions:['Where should AI enter first?','Which pilots deserve investment?','What should remain human-led?'],deliverables:['AI opportunity map','90-day transformation roadmap','Use-case scoring model']},agents:{code:'CAPABILITY / 02',title:'Agentic AI & Automation',copy:'Design human-plus-agent workflows that move beyond chat interfaces into governed execution, coordination, retrieval, and decision support.',questions:['Which work can become agentic?','Where should humans approve?','How much autonomy is appropriate?'],deliverables:['Agent workflow blueprint','Autonomy boundary map','Pilot implementation plan']},data:{code:'CAPABILITY / 03',title:'Data & AI Readiness',copy:'Assess whether enterprise data and knowledge are accessible, trustworthy, contextual, and structured enough for reliable AI use.',questions:['Can AI find the right context?','Which sources are authoritative?','Where are access and quality gaps?'],deliverables:['AI-readiness assessment','Knowledge/data map','Remediation priorities']},governance:{code:'CAPABILITY / 04',title:'AI Governance & Risk',copy:'Move governance from static policy documents into enforceable operating controls, ownership, observability, and escalation design.',questions:['What may AI decide alone?','How are actions audited?','What happens when systems fail?'],deliverables:['Governance operating model','Control framework','Monitoring & escalation plan']},modernization:{code:'CAPABILITY / 05',title:'Technology Modernization',copy:'Align cloud, software, architecture, security, and vendor choices with an AI-enabled operating model without adding unnecessary complexity.',questions:['What should be consolidated?','What architecture must change?','Where is cloud spend leaking value?'],deliverables:['Modernization roadmap','Vendor/platform evaluation','Target-state architecture brief']}};
qsa('.capability-tab').forEach(btn=>btn.addEventListener('click',()=>{qsa('.capability-tab').forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');const d=capabilities[btn.dataset.capability];qs('#capability-code').textContent=d.code;qs('#capability-title').textContent=d.title;qs('#capability-copy').textContent=d.copy;qs('#capability-questions').innerHTML=d.questions.map(x=>`<li>${x}</li>`).join('');qs('#capability-deliverables').innerHTML=d.deliverables.map(x=>`<li>${x}</li>`).join('')}));

const signalCopy={governance:{title:'Agent governance',copy:'As agent autonomy rises, organizations need enforceable limits, monitoring, audit trails, and human escalation—not just policy PDFs.',move:'MOVE → control architecture'},data:{title:'AI-ready data',copy:'Enterprise AI is increasingly constrained by whether information is searchable, reusable, permissioned, and rich in business context.',move:'MOVE → knowledge infrastructure'},cost:{title:'Cloud & model economics',copy:'AI value can disappear inside duplicated tools, unmanaged inference, oversized architectures, and pilots that never earn their operating cost.',move:'MOVE → AI FinOps'},security:{title:'AI security',copy:'Models and agents add new pathways for data leakage, prompt injection, privilege misuse, automated error, and AI-enabled attacks.',move:'MOVE → security by design'}};
qsa('.signal-row').forEach(btn=>btn.addEventListener('click',()=>{qsa('.signal-row').forEach(b=>b.classList.remove('is-active'));btn.classList.add('is-active');const d=signalCopy[btn.dataset.signal];const f=qs('.signal-feature');f.querySelector('h3').textContent=d.title;f.querySelector('p').textContent=d.copy;f.querySelector('strong').textContent=d.move}));

const backdrop=qs('#diagnostic-backdrop'),stage=qs('#diagnostic-stage'),bar=qs('#diagnostic-progress-bar');const questions=[{q:'How far has your organization moved beyond AI experimentation?',options:[['Mostly exploring',1],['A few pilots',2],['Multiple teams are using AI',3],['AI is embedded in operations',4]]},{q:'How well are your highest-value workflows documented?',options:[['Mostly tribal knowledge',1],['Some processes are mapped',2],['Core workflows are mapped',3],['Workflows are actively measured and redesigned',4]]},{q:'How ready is your enterprise data for AI use?',options:[['Fragmented / unclear',1],['Usable with manual effort',2],['Generally accessible and trusted',3],['Contextual, governed, and reusable',4]]},{q:'How mature are your AI controls and governance?',options:[['Not defined yet',1],['Basic policy exists',2],['Roles and review processes exist',3],['Technical controls, monitoring, and auditability exist',4]]},{q:'How clearly do you measure business value from AI?',options:[['We do not yet',1],['Mostly anecdotal',2],['Some use cases have KPIs',3],['Value is tracked across the AI portfolio',4]]}];let step=0,scores=[];
function renderDiagnostic(){if(!stage||!bar)return;bar.style.width=`${Math.min(step/questions.length*100,100)}%`;if(step>=questions.length){const total=scores.reduce((a,b)=>a+b,0),pct=Math.round((total/(questions.length*4))*100);let title='Build the foundation first',copy='Your strongest next move is likely workflow clarity, data readiness, and a focused AI roadmap before scaling more tools.';if(pct>=45){title='Move from pilots to a system';copy='You have enough foundation to prioritize use cases, redesign workflows, and establish governance for broader adoption.'}if(pct>=70){title='You are ready to scale deliberately';copy='The opportunity now is portfolio governance, agent operating models, stronger control architecture, and rigorous value measurement.'}stage.innerHTML=`<div class="diagnostic-result"><span class="diagnostic-score">${pct}</span><small>AI READINESS SIGNAL / 100</small><h3>${title}</h3><p>${copy}</p><a class="button" href="#contact" id="diagnostic-contact">Discuss this result</a></div>`;bar.style.width='100%';qs('#diagnostic-contact')?.addEventListener('click',closeDiagnostic);return}const item=questions[step];stage.innerHTML=`<div class="diagnostic-question"><small>QUESTION ${String(step+1).padStart(2,'0')} / ${String(questions.length).padStart(2,'0')}</small><h3>${item.q}</h3><div class="diagnostic-options">${item.options.map(([label,val])=>`<button type="button" data-value="${val}">${label}</button>`).join('')}</div></div>`;qsa('.diagnostic-options button',stage).forEach(btn=>btn.addEventListener('click',()=>{scores.push(Number(btn.dataset.value));step++;renderDiagnostic()}))}
function openDiagnostic(){if(!backdrop)return;step=0;scores=[];backdrop.hidden=false;document.body.style.overflow='hidden';renderDiagnostic()}function closeDiagnostic(){if(!backdrop)return;backdrop.hidden=true;document.body.style.overflow=''}
['#open-diagnostic','#hero-diagnostic','#lab-diagnostic','#contact-diagnostic'].forEach(id=>qs(id)?.addEventListener('click',openDiagnostic));qs('#close-diagnostic')?.addEventListener('click',closeDiagnostic);backdrop?.addEventListener('click',e=>{if(e.target===backdrop)closeDiagnostic()});addEventListener('keydown',e=>{if(e.key==='Escape'&&!backdrop?.hidden)closeDiagnostic()});

const form=qs('#contact-form');if(form){form.addEventListener('submit',async e=>{e.preventDefault();const status=qs('#form-status'),button=qs('#submit-button');button.disabled=true;button.textContent='Sending…';status.textContent='';try{const res=await fetch(form.action,{method:'POST',body:new FormData(form),headers:{Accept:'application/json'}});if(!res.ok)throw new Error('Submission failed');form.reset();status.textContent='Received. We will follow up using the email you provided.'}catch(err){status.textContent='The form could not send. Please email realjjemail@gmail.com directly.'}finally{button.disabled=false;button.textContent='Send consulting inquiry'}})}